server {
    listen 80;
    server_name localhost;
    access_log off;
    client_max_body_size 32m;
    location / {
        proxy_pass http://wordpress:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto http;
    }
}
server {
    listen 8081;
    server_name localhost;
    access_log off;
    location / {
        proxy_pass http://mailpit:8025;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
